# -*- coding: utf-8 -*-
# このスクリプトを実行すると、同じフォルダに「毎日実行.bat」が正しく生成されます
import pathlib

bat = '@echo off\r\nsetlocal enabledelayedexpansion\r\nchcp 932 > nul\r\ncd /d "C:\\Users\\user\\Desktop\\データ収集"\r\n\r\nSET PYTHON="C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python314\\python.exe"\r\n\r\nset "JCD_01=桐生"\r\nset "JCD_02=戸田"\r\nset "JCD_03=江戸川"\r\nset "JCD_04=平和島"\r\nset "JCD_05=多摩川"\r\nset "JCD_06=浜名湖"\r\nset "JCD_07=蒲郡"\r\nset "JCD_08=常滑"\r\nset "JCD_09=津"\r\nset "JCD_10=三国"\r\nset "JCD_11=びわこ"\r\nset "JCD_12=住之江"\r\nset "JCD_13=尼崎"\r\nset "JCD_14=鳴門"\r\nset "JCD_15=丸亀"\r\nset "JCD_16=児島"\r\nset "JCD_17=宮島"\r\nset "JCD_18=徳山"\r\nset "JCD_19=下関"\r\nset "JCD_20=若松"\r\nset "JCD_21=芦屋"\r\nset "JCD_22=福岡"\r\nset "JCD_23=唐津"\r\nset "JCD_24=大村"\r\n\r\nset "JCD=%~1"\r\nif "!JCD!"=="" (\r\n    echo.\r\n    echo 1=桐生  2=戸田   3=江戸川 4=平和島\r\n    echo 5=多摩川 6=浜名湖 7=蒲郡  8=常滑\r\n    echo 9=津    10=三国  11=びわこ 12=住之江\r\n    echo 13=尼崎 14=鳴門  15=丸亀  16=児島\r\n    echo 17=宮島 18=徳山  19=下関  20=若松\r\n    echo 21=芦屋 22=福岡  23=唐津  24=大村\r\n    echo.\r\n    set /p JCD=会場コード: \r\n)\r\n\r\nif 1!JCD! LSS 110 set "JCD=0!JCD!"\r\ncall set "VENUE=%%JCD_!JCD!%%"\r\nif "!VENUE!"=="" ( echo 会場コードが不正です: !JCD! & pause & exit /b 1 )\r\n\r\nset "RACE="\r\nset "USER_RACE=%~2"\r\nif "!USER_RACE!"=="" ( set /p USER_RACE=レース番号(全レースはEnter): )\r\nif /I "!USER_RACE!"=="all" set "USER_RACE="\r\nif not "!USER_RACE!"=="" set "RACE=--race !USER_RACE!"\r\n\r\necho.\r\nset /p ANS_NEWS=新聞を作成しますか？ [y/N]: \r\nset "NEWSPAPER_FLAG="\r\nif /I "!ANS_NEWS!"=="y" set "NEWSPAPER_FLAG=--newspaper"\r\n\r\nif /I "!ANS_NEWS!"=="y" (\r\n    echo.\r\n    set /p ANS_PNG=PNGも発行しますか？ [y/N]: \r\n    if /I "!ANS_PNG!"=="y" set "NEWSPAPER_FLAG=--newspaper --png"\r\n)\r\n\r\necho.\r\necho ============================================================\r\necho  会場: !VENUE!  !RACE!  !NEWSPAPER_FLAG!\r\necho ============================================================\r\n\r\necho.\r\necho [Step 1] lzh_to_csv...\r\n%PYTHON% scripts\\lzh_to_csv.py --venue "!VENUE!" !RACE!\r\necho [OK] lzh_to_csv.py\r\n\r\necho.\r\necho [Step 2] update_master...\r\n%PYTHON% scripts\\update_master.py\r\nif !errorlevel! neq 0 ( echo [FAILED] update_master.py & pause & exit /b 1 )\r\necho [OK] update_master.py\r\n\r\necho.\r\necho [Step 3] load_race...\r\n%PYTHON% scripts\\load_race.py --venue !VENUE! !RACE! !NEWSPAPER_FLAG!\r\nif !errorlevel! neq 0 ( echo [FAILED] load_race.py & pause & exit /b 1 )\r\necho [OK] load_race.py\r\n\r\necho.\r\necho ============================================================\r\necho  完了！  %date% %time%\r\necho ============================================================\r\necho.\r\npause'

out = pathlib.Path(__file__).parent / '毎日実行.bat'
out.write_bytes(bat.encode('shift-jis'))
print('生成完了:', out)
input('Enterキーで閉じる')